import { Theme } from "@radix-ui/themes";
import type { Metadata } from "next";
import "./globals.css";

import AuthProvider from "@/components/auth/auth-provider";
import { authOptions } from "@/lib/auth";
import "@radix-ui/themes/styles.css";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  if (!session) {
    redirect("/api/auth/signin");
  }

  return (
    <html lang="en">
      <body>
        <Theme
          appearance="dark"
          accentColor="lime"
          grayColor="slate"
          hasBackground
          panelBackground="translucent"
        >
          <AuthProvider session={session}>{children}</AuthProvider>
        </Theme>
      </body>
    </html>
  );
}
